export const RECOMPENSAS = [
  { id: 'taza',            nombre: 'Taza Fisiter',           costo: 100 },
  { id: 'polera',          nombre: 'Polera Deportiva',       costo: 180 },
  { id: 'botella',         nombre: 'Botella de Agua 1 L',    costo: 200 },
  { id: 'mat',             nombre: 'Mat de Yoga',            costo: 220 },
  { id: 'dia-libre',       nombre: 'Día Libre',              costo: 500 },
  { id: 'gift20',          nombre: 'Gift Card $20 000',      costo: 700 },
  { id: 'gift50',          nombre: 'Gift Card $50 000',      costo: 1500 },
  { id: 'audifonos',       nombre: 'Audífonos Bluetooth',    costo: 900 },
  { id: 'smartband',       nombre: 'Smartband',              costo: 1300 },
  { id: 'rueda-abdominal', nombre: 'Rueda Abdominal',        costo: 250 },
  { id: 'kettlebell',      nombre: 'Kettlebell 8 kg',        costo: 400 },
  { id: 'colchoneta',      nombre: 'Colchoneta Plegable',    costo: 240 },
  { id: 'pesas',           nombre: 'Set de Pesas 5 kg',      costo: 350 },
  { id: 'clase-yoga',      nombre: 'Clase de Yoga Online',   costo: 150 },
  { id: 'clase-box',       nombre: 'Clase de Box Fitness',   costo: 180 },
  { id: 'proteina',        nombre: 'Proteína (1 kg)',        costo: 600 },
  { id: 'bicicleta-sp',    nombre: 'Bicicleta Spinning',     costo: 3200 },
  { id: 'soga',            nombre: 'Soga para Saltar',       costo: 120 },
  { id: 'fitball',         nombre: 'Pelota de Estabilidad',  costo: 260 },
  { id: 'masaje',          nombre: 'Sesión de Masaje 45 min',costo: 800 },
];
